# Generated by Django 5.2.5 on 2025-12-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebalanceevent',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
