# Generated by Django 5.2.5 on 2025-12-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='snaptrade_user_secret',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
